=== Robotics-Research-Group-KUL/crospi_core/deleteme_scripts_old/schema/tasks/move-circle.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "$id": "move-circle.json",
    "title": "Circular trajectory",
    "description": "Move a robot on a circular trajectory.",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "string":{
            "type":"string",
            "default":"move-circle"
        },
        "task": {
            "type": "object",
            "properties": {
                "radius": {
                    "description": "radius of the circular trajectory in [m]",
                    "type": "number"
                },
                "velocity": {
                    "description":"velocity along the circular trajectory in [m/s]",
                    "type": "number"
                },
                "worldmodel": {
                    "description":"JSON worldmodel describing the robot and its environment",
                    "type":"string",
                    "interpolate": true,
                    "default":"$[etasl_ros2]/scripts/worldmodels/ur10_robot.json"
                }
            },
            "additionalProperties": false,
            "required": [
                "radius",
                "velocity",
                "worldmodel"
            ]
        },
        "etaslfile": {
            "description": "etaslfile, you normally leave this to the default",
            "type": "string",
            "default": "$[etasl_ros2]/scripts/etasl/move_circle.lua",
            "interpolate": true
        },
        "etasl": {
            "title": "eTaSL",
            "description": "optional parameters to tune eTaSL",
            "$ref": "../etasl.json"
        }
    },
    "additionalProperties": false
}

=== Robotics-Research-Group-KUL/crospi_core/yaml_files/tst.json
{
   "$schema" : "../schema/tasks/move-circle.json",
   "etasl" : {
      "initializer" : {
         "convergence_criterion" : 1e-08,
         "duration" : 3.0,
         "full" : true,
         "sample_time" : 0.01,
         "weightfactor" : 10000.0
      },
      "inputhandlers" : [
         {
            "depth" : 1,
            "is-jointstateinputhandler" : true,
            "number_of_tries" : 200,
            "topic-name" : "joint_states"
         }
      ],
      "outputhandlers" : [
         {
            "is-tfoutputhandler" : true,
            "tf" : [
               {
                  "frame_id" : "world",
                  "variable-names" : [ "wp" ]
               }
            ]
         },
         {
            "is-jointstateoutputhandler" : true,
            "topic-name" : "velcmd"
         }
      ],
      "reporting_interval" : 3,
      "sample_time" : 0.01,
      "solver" : {
         "cputime" : 100,
         "is-qpoasessolver" : true,
         "nWSR" : 100,
         "regularization_factor" : 1e-08
      }
   },
   "etaslfile" : "/workspaces/colcon_ws/install/etasl_ros2/share/etasl_ros2/scripts/etasl/move_circle.lua",
   "string" : "move-circle",
   "task" : {
      "radius" : 0.10000000000000001,
      "velocity" : 0.10000000000000001,
      "worldmodel" : "/workspaces/colcon_ws/install/etasl_ros2/share/etasl_ros2/scripts/worldmodels/worldmodel.json"
   }
}
